// <auto-generated />
using LocalBusinessLookup.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LocalBusinessLookup.Migrations
{
    [DbContext(typeof(LocalBusinessLookupContext))]
    [Migration("20200821180601_RestaurantSeedData")]
    partial class RestaurantSeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("LocalBusinessLookup.Models.Restaurant", b =>
                {
                    b.Property<int>("RestaurantId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address");

                    b.Property<string>("City");

                    b.Property<string>("Cuisine");

                    b.Property<string>("Name");

                    b.Property<string>("PhoneNumber");

                    b.Property<string>("State");

                    b.HasKey("RestaurantId");

                    b.ToTable("Restaurants");

                    b.HasData(
                        new
                        {
                            RestaurantId = 1,
                            Address = "203 Villa Rd",
                            City = "Newberg",
                            Cuisine = "American(Traditional)",
                            Name = "Newbergundian Bistro",
                            PhoneNumber = "971-832-8687",
                            State = "OR"
                        },
                        new
                        {
                            RestaurantId = 2,
                            Address = "910 E 1st St",
                            City = "Newberg",
                            Cuisine = "Thai, Food Tucks",
                            Name = "Bangkok Noi Thai",
                            PhoneNumber = "503-726-6067",
                            State = "OR"
                        },
                        new
                        {
                            RestaurantId = 3,
                            Address = "808 E Hancock St",
                            City = "Newberg",
                            Cuisine = "Coffee & Tea, Bakeries",
                            Name = "Coffee Cottage",
                            PhoneNumber = "503-538-5126",
                            State = "OR"
                        },
                        new
                        {
                            RestaurantId = 4,
                            Address = "3777 Portland Rd",
                            City = "Newberg",
                            Cuisine = "Russian, Coffee & Tea",
                            Name = "From Russia With Love",
                            PhoneNumber = "971-832-8579",
                            State = "OR"
                        },
                        new
                        {
                            RestaurantId = 5,
                            Address = "155 SW 7th St",
                            City = "Dundee",
                            Cuisine = "Sandwiches, Pizza",
                            Name = "Red Hills Market",
                            PhoneNumber = "971-832-8414",
                            State = "OR"
                        });
                });

            modelBuilder.Entity("LocalBusinessLookup.Models.Shop", b =>
                {
                    b.Property<int>("ShopId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address");

                    b.Property<string>("Category");

                    b.Property<string>("City");

                    b.Property<string>("Name");

                    b.Property<string>("PhoneNumber");

                    b.Property<string>("State");

                    b.HasKey("ShopId");

                    b.ToTable("Shops");
                });
#pragma warning restore 612, 618
        }
    }
}
