// <auto-generated />
using LocalBusinessLookup.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LocalBusinessLookup.Migrations
{
    [DbContext(typeof(LocalBusinessLookupContext))]
    [Migration("20200821185906_ShopSeedData")]
    partial class ShopSeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("LocalBusinessLookup.Models.Restaurant", b =>
                {
                    b.Property<int>("RestaurantId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address");

                    b.Property<string>("City");

                    b.Property<string>("Cuisine");

                    b.Property<string>("Name");

                    b.Property<string>("PhoneNumber");

                    b.Property<string>("State");

                    b.HasKey("RestaurantId");

                    b.ToTable("Restaurants");

                    b.HasData(
                        new
                        {
                            RestaurantId = 1,
                            Address = "203 Villa Rd",
                            City = "Newberg",
                            Cuisine = "American(Traditional)",
                            Name = "Newbergundian Bistro",
                            PhoneNumber = "971-832-8687",
                            State = "OR"
                        },
                        new
                        {
                            RestaurantId = 2,
                            Address = "910 E 1st St",
                            City = "Newberg",
                            Cuisine = "Thai, Food Tucks",
                            Name = "Bangkok Noi Thai",
                            PhoneNumber = "503-726-6067",
                            State = "OR"
                        },
                        new
                        {
                            RestaurantId = 3,
                            Address = "808 E Hancock St",
                            City = "Newberg",
                            Cuisine = "Coffee & Tea, Bakeries",
                            Name = "Coffee Cottage",
                            PhoneNumber = "503-538-5126",
                            State = "OR"
                        },
                        new
                        {
                            RestaurantId = 4,
                            Address = "3777 Portland Rd",
                            City = "Newberg",
                            Cuisine = "Russian, Coffee & Tea",
                            Name = "From Russia With Love",
                            PhoneNumber = "971-832-8579",
                            State = "OR"
                        },
                        new
                        {
                            RestaurantId = 5,
                            Address = "155 SW 7th St",
                            City = "Dundee",
                            Cuisine = "Sandwiches, Pizza",
                            Name = "Red Hills Market",
                            PhoneNumber = "971-832-8414",
                            State = "OR"
                        });
                });

            modelBuilder.Entity("LocalBusinessLookup.Models.Shop", b =>
                {
                    b.Property<int>("ShopId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address");

                    b.Property<string>("Category");

                    b.Property<string>("City");

                    b.Property<string>("Name");

                    b.Property<string>("PhoneNumber");

                    b.Property<string>("State");

                    b.HasKey("ShopId");

                    b.ToTable("Shops");

                    b.HasData(
                        new
                        {
                            ShopId = 1,
                            Address = "117 S College St",
                            Category = "Cards & Stationery",
                            City = "Newberg",
                            Name = "Pulp & Circumstance",
                            PhoneNumber = "971-264-0563",
                            State = "OR"
                        },
                        new
                        {
                            ShopId = 2,
                            Address = "602 E 1st St",
                            Category = "Women's clothing",
                            City = "Newberg",
                            Name = "Nikki Jane's Boutique",
                            PhoneNumber = "503-538-2620",
                            State = "OR"
                        },
                        new
                        {
                            ShopId = 3,
                            Address = "23855 SW 195th Pl",
                            Category = "Gift Shops, Holiday Decorations",
                            City = "Sherwood",
                            Name = "Sleighbells Farm & Gift Shop",
                            PhoneNumber = "503-625-6052",
                            State = "OR"
                        },
                        new
                        {
                            ShopId = 4,
                            Address = "22275 SW Pacific Hwy",
                            Category = "Antiques",
                            City = "Sherwood",
                            Name = "Unger's Trading Post",
                            PhoneNumber = "503-625-7834",
                            State = "OR"
                        },
                        new
                        {
                            ShopId = 5,
                            Address = "110 SW 7th St",
                            Category = "Women's Clothing",
                            City = "Dundee",
                            Name = "Joy's Uptown Style",
                            PhoneNumber = "503-223-3400",
                            State = "OR"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
